services:
  db:
    image: postgres:16
    container_name: fleetflow_db
    restart: always
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
